blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.list_view, name='blog'),
    path('post/<pk>/<title>/', views.post_view, name='blog-detail'),
    path('category/<pk>/<title>/', views.category_view, name='category-view'),
    path('tag/<pk>/<name>/', views.tag_view, name='tag-view'),
    path('search/', views.search, name='search-result'),
    path('view/<pk>/', views.comment_view, name="comments-view"),
    path('add-comment/<pk>/', views.add_comment, name="add-comment"),
    path('add-like/<pk>/', views.record_post_like, name="add-post-like"),
]

books/urls.py
from unicodedata import name
from django.urls import path

from . import views

urlpatterns = [
    path('', views.bookView, name='books-list'),
    path('detail/<pk>/<slug>/', views.bookView, name='books-view'),
    path('download/<pk>/<slug>/', views.handleSampleRequest, name='sample-download'),
    path("add-to-cart/<pk>/", views.addToCart, name='add-to-cart'),
    path("cart/", views.cart_view, name='cart-view'),
    path('checkout/', views.checkout_view, name='checkout-view'),
    path("book-download/<token>/", views.book_download, name='book-download'),
    path("book/detail/<pk>/<slug>/", views.bookDetail, name="book-view"),
    path('payment-check', views.payment_check, name='payment-check'),
    path('validate/<token>/', views.validateEmail, name='validate-email'),
    path("reset-session/", views.resetSession, name='reset-session')


]

isaniro/urls.py
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

sitemaps = {
    "posts": PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
        path("__reload__/", include("django_browser_reload.urls")),
    path('blog/', include(("blog.urls", 'blog'), namespace='blog')),
    path('user/', include("user.urls")),
    path("", include("index.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('book/', include("books.urls"))

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/forms.py
from django import forms

from books.models import Address, AnonymousAddress


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ["customer", 'created_at']

class AnonymousAddressForm(forms.ModelForm):
    class Meta:
        model=AnonymousAddress
        exclude=['session_key', 'created_at']

books/views.py
import json
from django.conf import settings
from django.core import signing
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.http import Http404, HttpResponse, HttpResponseForbidden
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.html import strip_tags
from books.forms import AddressForm, AnonymousAddressForm

from books.models import Address, AnonymousAddress, AnonymousOrder, AnonymousPayedBook, AnonymousPayment, Book, Customer, Order, OrderItem, PayedBook, Payment
from books.utils import cookieCart, handle_payment, notify_email, ref_code_generator, sign_book_token, verifyTransaction

# Create your views here.


def bookView(request, *args, **kwargs):
    books = Book.objects.filter(published=True)
    return render(request, 'pages/book.html', {'books': books})


def bookDetail(request, pk, *args, **kwargs):
    book = Book.objects.get(id=pk)
    return render(request, 'book-detail.html', {'book': book})


def send_sample(email, book, user, request):
    from django.template.loader import render_to_string
    html = render_to_string("email/sample_book.html", {'book': book, "user": user, "request": request}
                            )
    plain = strip_tags(html)
    EmailFrom = "'Isaniro Books'<books@isaniro.com>"
    mail = EmailMultiAlternatives("Incamake y'igitabo '%s'" %
                                  book.title, html, EmailFrom, [email])
    mail.attach_alternative(html, "text/html")
    # mail.subject = "Incamake y'igitabo '%s'" % book.title
    # mail.body = html
    mail.attach_file(book.sample.path)
    # mail.to([email])
    mail.send(fail_silently=True)


def handleSampleRequest(request, pk, *args, **kwargs):
    book = get_object_or_404(Book, pk=pk)
    name = request.GET.get('name')
    email = request.GET.get('email')
    user = {"name": name, 'email': email}

    send_sample(email, book, user, request)
    return JsonResponse({"sent": True, "title": book.title})


def book_download(request, token, *args, **kwargs):
    signer = signing.TimestampSigner(
        key=settings.BOOK_SIGNATURE, salt="isaniro")
    try:
        data = signer.unsign_object(token)
        book = Book.objects.get(id=data['book'])
        return redirect(book.download_link)
    except Exception:
        print(Exception)
        return HttpResponseForbidden("Expired link")


def cart_view(request):
    if request.user.is_authenticated:
        customer, created = Customer.objects.get_or_create(user=request.user)
        order, created = Order.objects.get_or_create(
            customer=customer, completed=False)
        items = order.orderitem_set.all()
        cart_total = order.get_cart_total
        cart_quantity = order.get_cart_items
        context = {
            'items': items,
            'cart_total': cart_total,
            'cart_quantity': cart_quantity
        }

        return render(request, "cart.html", context)
    else:
        try:
            cart = json.loads(request.COOKIES['cart'])
        except:
            cart = {}
        cookie_cart = cookieCart(request)
        context = {
            'items': cookie_cart['items'],
            'cart_total': cookie_cart['cart_total'],
            'cart_quantity': cookie_cart['cart_quantity']
        }
        return render(request, "cart.html", context)


def addToCart(request, pk):
    book = Book.objects.get(id=pk)
    if not book.downloadable_copy:
        return HttpResponseForbidden("The book is not available")
    action = request.GET.get('action')
    if book:
        if request.user.is_authenticated:
            customer, created = Customer.objects.get_or_create(
                user=request.user)
            order, created = Order.objects.get_or_create(
                customer=customer, completed=False)
            orderItem, created = OrderItem.objects.get_or_create(
                order=order, product=book)
            if action == 'remove':
                orderItem.delete()
            else:
                orderItem.quantity = 1
                orderItem.save()
            return redirect("cart-view")
        else:
            return redirect("cart-view")
    return Http404("Not found")


def checkout_view(request):
    if request.user.is_authenticated:
        customer, created = Customer.objects.get_or_create(user=request.user)
        order, created = Order.objects.get_or_create(
            customer=customer, completed=False)
        if created:
            cookie_items = cookieCart(request)
            for item in cookie_items:
                try:
                    product = Book.objects.get(id=item['id'])
                    orderItem = OrderItem.objects.create(
                        product=product, order=order, quantity=item['quantity'])

                except:
                    pass

        items = order.orderitem_set.all()
        cart_total = order.get_cart_total
        cart_quantity = order.get_cart_items
        try:
            address = Address.objects.get(customer=customer)
            form = AddressForm(instance=address)
        except Exception:
            form = AddressForm()
        context = {
            'items': items,
            'cart_total': cart_total,
            'cart_quantity': cart_quantity,
            'form': form
        }

        if request.method == 'POST':
            try:
                address = Address.objects.get(customer=customer)
                form = AddressForm(request.POST, instance=address)
            except:
                form = AddressForm(request.POST)
            if not form.is_valid():
                context['form'] = form
                return render(request, 'checkout.html', context)
            if form.is_valid():
                print('Valid')

                address = form.save(commit=False)

                address.customer = customer
                address = address.save()
                print(address)
                host = request.get_host()
                protocol = request.scheme
                redirect_url = "%s://%s/book/payment-check" % (protocol, host)
                data = {
                    'transaction_id': order.order_id,
                    'get_cart_total': order.get_cart_total,
                    'customer_id': order.customer.user.id,
                    'customer_email': order.customer.user.email,
                    'name': order.customer.user.get_full_name(),
                }
                print(order.order_id)
                link = handle_payment(data, redirect_url)
                return JsonResponse({"link": link})

        return render(request, 'checkout.html', context)
    else:
        try:
            cart = json.loads(request.COOKIES['cart'])
        except:
            cart = {}
        cookie_cart = cookieCart(request)
        try:
            if not request.session.session_key:
                request.session.save()
            address = AnonymousAddress.objects.get(
                session_key=request.session.session_key)
        except:
            address = None
        form = AnonymousAddressForm(instance=address)
        context = {
            'items': cookie_cart['items'],
            'cart_total': cookie_cart['cart_total'],
            'cart_quantity': cookie_cart['cart_quantity'],
            'form': form
        }
        if request.method == 'POST':
            print(address)
            if address:
                form = AnonymousAddressForm(request.POST, instance=address)
            else:
                form = AnonymousAddressForm(request.POST)
            if form.is_valid():
                address = form.save(commit=False)
                if not request.session.session_key:
                    request.session.save()
                address.session_key = request.session.session_key
                address.save()
                order, created = AnonymousOrder.objects.get_or_create(
                    address=address, completed=False)
                if created:
                    for item in cookie_cart['items']:
                        try:
                            book = Book.objects.get(id=item.product.id)
                            order.products.add(book)
                            order.save()
                        except:
                            pass
                host = request.get_host()
                protocol = request.scheme
                print(address)
                redirect_url = "%s://%s/book/payment-check" % (protocol, host)
                data = {
                    'transaction_id': order.order_id,
                    'get_cart_total': cookie_cart['cart_total'],
                    'customer_id': ref_code_generator(),
                    'customer_email': address.email,
                    'name': address.full_name,
                    'telephone': address.telephone
                }
                print(order.order_id)
                link = handle_payment(data, redirect_url)
                return JsonResponse({"link": link})
            else:
                context['form'] = form
                return render(request, 'checkout-anonymous.html', context)
        return render(request, 'checkout-anonymous.html', context)


def provisionBooks(customer, payment, order):
    items = order.orderitem_set.all()
    for item in items:
        payedbook = PayedBook.objects.get_or_create(
            customer=customer, payment=payment, book=item.product)
    context = {

    }
    notify_email('email/download_book.html', customer.user.email, {})
    return True


def payment_check(request):
    status = request.GET.get('status', None)
    tx_ref = request.GET.get('tx_ref', None)
    tx_id = request.GET.get('transaction_id', None)
    info = verifyTransaction(tx_id)
    if info['data'] and info['data']['status'] == 'successful':
        if request.user.is_authenticated:
            try:

templates/pages/book.html
{% extends "layout/base.html" %}
{% load static %}
{% load humanize %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/book.css' %}" class="css">
<style>
    .px-4 {
        padding: inherit 4rem !important;
    }

    .w-300 {
        max-width: 300px;
    }

    .h-400 {
        max-height: 400px;
    }

    .contain {
        object-fit: contain;
    }

    .w-full {
        width: 100%;
    }

    .h-full {
        height: 100%;
    }

    .row {
        display: flex;
        flex-direction: row;
    }

    .card .row {
        padding: 2rem 4rem;
    }

    .col-md-6 {
        width: 50%;
    }

    .flex-col {
        display: flex;
        flex-direction: column;
    }

    .justify-center {
        justify-content: center;
    }

    .btn {
        padding: .5rem 1rem;
        border-radius: 5px;
        box-shadow: 0px 0px 2px 3px rgba(128, 128, 128, 0.226);
        transition: .3s;
    }

    .btn:hover {
        transition: .3s;
    }

    .title {
        padding-left: 1rem;
        margin: 1rem;
    }

    .text-danger {
        color: red;
    }

    #book-list {
        padding: 2rem 2rem;
    }

    .book-div {
        height: 350px;
        width: 250px;
        justify-content: center;
        text-align: center;
        margin: 5px;
        box-shadow: 0px 0px 4px 4px rgba(128, 128, 128, 0.637);
        padding: .5rem;
        border-radius: 5px;
    }

    .book-div .img {
        height: 60%;
        width: 100%;
    }

    .buy-btn {
        margin-top: 1rem;
    }

    .book-div img {
        height: 100%;
        width: 100%;
        object-fit: cover;
    }

    .book-div .info {
        height: 40%;
        align-items: center;
    }

    .overlay {
        position: absolute;
        bottom: 0px;
        background-color: rgb(90, 24, 24);
    }
</style>

{% endblock style %}
{% block title %}
Ibitabo
{% endblock title %}
{% block content %}


<main>
    <div class="hero">
        <div class="text">
            <h2>Ibitabo bifasha urubyiruko</h2>
            <p>Twandika ibitabo bigufasha mu ngeri zitandukanye z'ubuzima.</p>
            <button class="btn-book btn-book-explore" onclick="window.location.href='#book-list'">REBA IBITABO</button>
        </div>
        <div class="carousel">
            {% for book in books %}


            <div class="book-card">
                <div class="book-cover-hero">
                    <img src="{{book.cover.url}}" alt="">
                </div>
                <div class="book-info">
                    <div class="h3 title">{{book.title}}</div>
                </div>
                <div class="progress">

                </div>
                <div class="explore">
                    <button class="btn btn-primary" onclick="window.location.href='#book-list'">SOMA</button>
                </div>


            </div>
            {% endfor %}

        </div>


    </div>
    <section id="book-list">
        <div class="row flex-row">

            {% for book in books %}
            <div class="book-div">
                <div class="img relative">
                    <img class="h-full w-full contain" src="{{book.imgURL}}" alt="">

                </div>
                <div class="info">
                    <h3 class="title"><a href="{{book.get_absolute_url}}">{{book.title}}</a></h3>
                    <div class="pricing">
                        {% if book.on_discount %}
                        <p>
                            <strike class="text-danger">{{book.price|intcomma}}</strike>
                            <span><b>{{book.discounted_price| intcomma}}
                                    Rwf</b></span>
                        </p>

                        {% else %}
                        <p>Price: {{book.price | intcomma}} Rwf</p>
                        {% endif %}
                    </div>
                    <div class="buy-btn">
                        <a href="{{book.get_cart_url}}" data-pk="{{book.id}}" class="btn btn-primary update-cart">BUY
                            NOW</a>
                    </div>
                </div>
            </div>

            {% endfor %}

        </div>
    </section>
</main>

{% endblock content %}

{% block script %}

<script>
    $(document).ready(() => {
        $('.request-sample').click((e) => {
            let url = e.target.getAttribute('data-url')
            e.preventDefault()
            Swal.fire({
                title: 'Uzuza iyi form ubone incamake',
                html:
                    `<input type="text" id="swal-input1" class="swal2-input" placeholder='Amazina' required> 
                    '<input type="email" id="swal-input2" class="swal2-input" placeholder='Email' required>`,
                preConfirm: function () {
                    return new Promise(function (resolve) {
                        // Validate input
                        if ($('#swal-input1').val() == '' || $('#swal-input2').val() == '' || !$('#swal-input2').val().match(/\S+@\S+\.\S+/)) {
                            swal.showValidationMessage("Uzuza amakuru hose"); // Show error when validation fails.
                            swal.enableButtons()// Enable the confirm button again.
                        } else {
                            swal.resetValidationMessage(); // Reset the validation message.
                            resolve([
                                $('#swal-input1').val(),
                                $('#swal-input2').val()
                            ]);
                        }
                    })
                },
                onOpen: function () {
                    $('#swal-input1').focus()
                }


            }).then(function (result) {
                // If validation fails, the value is undefined. Break out here.
                if (typeof (result.value) == 'undefined') {
                    return false;
                }

                let data = { "name": result.value[0], 'email': result.value[1] }
                console.log(data)
                $.ajax({
                    url: url,
                    data: data,
                    success: (res) => {
                        console.log(res)
                        new swal({
                            title: 'Incamake yoherejwe',
                            html: `Kuri <b>${data.name}</b> incamake wasabye y'igitabo <br>
                            <b>${res.title}</b> yoherejwe kuri Email yawe <b> ${data.email}</b>.<br>
                                Murakoze. <br><b>Ibuka kureba muri Junk/Spam folder yawe mugihe utabonye email</b>
                            `
                        })
                    },
                    error: (err) => {
                        console.log(err)
                        new swal({
                            title: 'Incamake ntiyoherejwe',
                            html: `Kuri <b>${data.name}</b> incamake wasabye y'igitabo <br>
                            <b>Ntabwo yoherejwe. Mutwihanganire mwongere kugerageza mukanya</b>
                            `
                        })
                    }
                })
                new swal(data)
            }).catch(swal.noop)
        })
    })
</script>
{% endblock script %}

templates/pages/categories.html
{% extends "layout/base.html" %}
{% load static %}
{% load humanize%}
{% load hitcount_tags %}


{% block content %}

<main>

    <section class="container">
        <div class="site-content">
            <div class="posts">
                {% for post in posts %}

                <div class="post-content" data-aos="zoom-in" data-aos-delay="200">
                    <div class="post-image">
                        <div>
                            <img src="{{post.thumbnail.url}}" class="img" alt="blog1">
                        </div>
                        <div class="post-info flex-row">
                            <span><i class="fas fa-user text-gray"></i>&nbsp;&nbsp;{{post.author.name}}</span>
                            <span><i class="fas fa-calendar-alt text-gray"></i>&nbsp;&nbsp;January 14, 2019</span>
                            <span>{% get_hit_count for post %} Views</span>
                        </div>
                    </div>
                    <div class="post-title">
                        <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                        <p>{{post.summary|safe}}
                        </p>
                        <button class="btn post-btn post-link" data-url="{{post.get_absolute_url}}">Soma &nbsp; <i
                                class="fas fa-arrow-right"></i></button>
                    </div>
                </div>
                <hr>
                {% empty%}
                <h2>Wihangane ntabwo twabonye ibyo washakishaga</h2>
                {% endfor %}

            </div>
            <aside class="sidebar">
                {% include "layout/cat.html" %}

                <div class="newsletter" data-aos="fade-up" data-aos-delay="300">
                    <h2>Newsletter</h2>
                    <div class="form-element">
                        <input type="text" class="input-element" placeholder="Email">
                        <button class="btn form-btn">Subscribe</button>
                    </div>
                </div>
                {% include "layout/tag.html" %}
            </aside>
        </div>
    </section>

    <!-- -----------x---------- Site Content -------------x------------>

</main>
{% endblock content %}

templates/pages/search.html
{% extends "layout/base.html" %}
{% load static %}
{% load humanize%}

{% block style %}
<style>
    .empty-div {
        padding: 3rem 2rem;
        text-align: center;
        font-family: var(--Lexend);
        margin: 3rem;
        box-shadow: 2px 2px 2px 2px grey;
    }

    .button-group {
        display: flex;
        justify-content: center;
        padding: 2rem;
        width: fit-content;
    }

    .button-group .btn {
        margin: 1rem 2rem;
        padding: 1rem 2rem;
        border-radius: 30px;
    }

    .btn-outline {
        border: 2px solid black;
        background-color: rgba(68, 68, 68, 0.247);
        color: black;
        transition: .3s all;
    }

    .btn-outline:hover {
        background-color: rgba(243, 243, 243, 0.473);

    }
</style>
{% endblock style %}

{% block content %}

<main>

    <section class="container">
        <div class="site-content">
            <div class="posts">
                {% for post in posts %}


                <div class="post-content" data-aos="zoom-in" data-aos-delay="200">
                    <div class="post-image">
                        <div>
                            <img src="{{post.thumbnail.url}}" class="img" alt="blog1">
                        </div>
                        <div class="post-info flex-row">
                            <span><i class="fas fa-user text-gray"></i>&nbsp;&nbsp;Admin</span>
                            <span><i class="fas fa-calendar-alt text-gray"></i>&nbsp;&nbsp;January 14, 2019</span>
                            <span>2 Commets</span>
                        </div>
                    </div>
                    <div class="post-title">
                        <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                        <p>{{post.summary|safe}}
                        </p>
                        <button class="btn post-btn post-link" data-url="{{post.get_absolute_url}}">Soma &nbsp; <i
                                class="fas fa-arrow-right"></i></button>
                    </div>
                </div>
                <hr>
                {% empty%}
                <div class="empty-div">
                    <h2>Wihangane ntabwo twabonye ibyo washakishaga</h2>
                    <div class="button-group">
                        <a href="{% url 'blog:blog' %}" class="btn btn-outline btn-blog">Subira kunkuru</a>
                        <a href="#prevented" class="btn btn-primary btn-blog search"
                            data-url="{% url 'blog:search-result'%}">Ongera Ushakishe</a>
                    </div>
                </div>

                {% endfor %}

            </div>
            <aside class="sidebar">
                {% include "layout/cat.html" %}



            </aside>
        </div>
    </section>

    <!-- -----------x---------- Site Content -------------x------------>

</main>
{% endblock content %}

templates/pages/services.html
{% extends "layout/base.html" %}
{% load cloudinary %}
{% block style %}
<style>
    .hero {
        padding: 2rem;
    }

    .hero .services-list {
        display: flex;
        justify-content: center;
        margin: 2rem 0rem;
        padding: 1rem 2rem;

    }

    .hero .services-list .card {
        max-width: 300px;
        min-width: 200px;
        margin: 0px 2rem;
        box-shadow: 2px 2px 2px 2px grey;
        border-radius: 10px;
        overflow-x: hidden;
        text-align: center;
        transition: .5s all;
        position: relative;

    }

    .hero .services-list .card:hover {
        transition: .5s;
        transform: scale(1.3);
    }

    .hero .services-list .card img {
        max-height: 200px;
        object-fit: cover;
        position: top;
        border-radius: 10px 10px 0px 0px;
    }

    /* .hero .services-list .card-middle {
        transform: scale(1.1);
        margin: 2rem 2rem;
        transition: .5s all;
    } */

    .hero .services-list .card-middle:hover {
        transform: scale(1.2);
        transition: .5s all;
    }

    .hero .services-list .card-middle .title {
        transform: scale(.7);
        margin-bottom: 4rem;
    }

    .learn-more {
        padding: 1rem;
        position: absolute;
        bottom: 0;
        margin-top: 2rem;
        left: 50%;
        transform: translateX(-50%);
        text-align: center;
        width: 100%;
    }

    .learn-more button {
        background-color: rgb(10, 126, 141);
        color: white;
        font-family: var(--Lexend);
        padding: .5rem 2rem;
        border-radius: 20px;
        transition: .5s all;
        border: none;
        min-width: fit-content;
    }

    .learn-more button:hover {
        box-shadow: 2px 2px 2px 2px blue;
    }
</style>

{% endblock style %}
{% block content %}



<div class="hero">
    <div class="services-list">

        {% for service in services %}
        <div class="service card">
            <div class="service-image">
                {% cloudinary service.picture1 crop="fill" height=200 width=300 %}
            </div>
            <div class="title">

            </div>
            <h2>{{ service.title }}</h2>
            <p>{{service.description}}</p>
        </div>
        {% endfor %}



    </div>
</div>

{% endblock content %}