blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.list_view, name='blog'),
    path('post/<pk>/<title>/', views.post_view, name='blog-detail'),
    path('category/<pk>/<title>/', views.category_view, name='category-view'),
    path('tag/<pk>/<name>/', views.tag_view, name='tag-view'),
    path('search/', views.search, name='search-result'),
    path('view/<pk>/', views.comment_view, name="comments-view"),
    path('add-comment/<pk>/', views.add_comment, name="add-comment"),
    path('add-like/<pk>/', views.record_post_like, name="add-post-like"),
]

books/urls.py
from unicodedata import name
from django.urls import path

from . import views

urlpatterns = [
    path('', views.bookView, name='books-list'),
    path('detail/<pk>/<slug>/', views.bookView, name='books-view'),
    path('download/<pk>/<slug>/', views.handleSampleRequest, name='sample-download'),
    path("add-to-cart/<pk>/", views.addToCart, name='add-to-cart'),
    path("cart/", views.cart_view, name='cart-view'),
    path('checkout/', views.checkout_view, name='checkout-view'),
    path("book-download/<token>/", views.book_download, name='book-download'),
    path("book/detail/<pk>/<slug>/", views.bookDetail, name="book-view"),
    path('payment-check', views.payment_check, name='payment-check'),
    path('validate/<token>/', views.validateEmail, name='validate-email'),
    path("reset-session/", views.resetSession, name='reset-session')


]

isaniro/urls.py
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

sitemaps = {
    "posts": PostSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
        path("__reload__/", include("django_browser_reload.urls")),
    path('blog/', include(("blog.urls", 'blog'), namespace='blog')),
    path('user/', include("user.urls")),
    path("", include("index.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),
    path('book/', include("books.urls"))

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms

from .models import Comment, Post


class CommentForm(forms.ModelForm):
    """Form definition for Comment."""

    class Meta:
        """Meta definition for Commentform."""

        model = Comment
        fields = ('name', "email", "body")


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'category', 'content',
                  'summary', 'tags']

blog/views.py
from django.contrib import messages
from django.core import paginator
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import DetailView, View
from rest_framework.response import Response
from rest_framework.views import APIView

from .forms import CommentForm
from .models import Category, Comment, Post, SearchTerms, Tag
from .serializer import CommentSerializer


class BlogListView(View):
    def get(self, *args, **kwargs):
        posts = Post.objects.filter(
            published=True)
        paginator = Paginator(posts, 7)
        page_var = "page"
        page = self.request.GET.get(page_var, 1)
        try:
            paginated_data = paginator.page(page)
        except PageNotAnInteger:
            paginated_data = paginator.page(1)
        except EmptyPage:
            paginated_data = paginator.page(paginator.num_pages)

        context = {
            'posts': paginated_data,
            "recent_posts": posts[:5],
            'tags': Tag.objects.all(),
            'categories': Category.objects.all(),
            'tags': Tag.objects.all(),
            'featured': posts[0]
        }

        return render(self.request, 'blog.html', context)


list_view = BlogListView.as_view()


def post_view(request, pk, *args, **kwargs):
    post = get_object_or_404(Post, pk=pk)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    posts = Post.objects.filter(
        published=True).exclude(pk=pk)[:5]

    context = {
        'post': post,
        'categories': categories,
        'tags': tags,
        'posts': posts
    }

    return render(request, 'detail.html', context)


def load_comments(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(post=post, approved=True)
    serialized = CommentSerializer(comments, many=True)
    return Response(serialized.data)


class GetPostComments(APIView):

    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        print(post.title)
        comments = Comment.objects.filter(approved=True, post=post)
        serialized = CommentSerializer(comments, many=True)
        return Response(serialized.data)


comment_view = GetPostComments.as_view()


def add_comment(request, pk, *args, **kwargs):
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=pk)
        comment = Comment()
        comment.name = request.POST.get("name")
        comment.email = request.POST.get("email")
        comment.body = request.POST.get("body")
        comment.approved = True
        comment.post = post
        comment.save()
        data = {"created": "true"}
        return JsonResponse(data)
    else:
        data = {"created": "false"}
        return JsonResponse(data)


def category_view(request, pk, *args, **kwargs):
    cat = get_object_or_404(Category, pk=pk)
    posts = Post.objects.filter(published=True, category=cat)
    context = {
        'posts': posts,
        'category': cat,
        'categories': Category.objects.all(),
        'tags': Tag.objects.all(),

    }
    return render(request, 'pages/categories.html', context)


def tag_view(request, pk, *args, **kwargs):
    tag = get_object_or_404(Tag, pk=pk)
    posts = tag.posts.filter(published=True)
    cats = Category.objects.all()
    context = {'posts': posts,
               'tag': tag,
               'tags': Tag.objects.all(),
               'categories': cats}
    return render(request, 'pages/categories.html', context)


def search(request, *args, **kwargs):
    query_set = Post.objects.filter(published=True)
    query = request.GET.get('q')
    categories = Category.objects.all()
    if query:
        queryset = query_set.filter(
            Q(title__icontains=query) | Q(content__icontains=query) | Q(tags__title__icontains=query) | Q(category__title__icontains=query) | Q(author__name__icontains=query)).distinct()

    context = {
        'posts': queryset,
        'query': query,
        'categories': categories
    }
    # terms = SearchTerms.objects.filter(Q(term__icontains=query))
    # if terms:
    #     t = {'terms': terms}
    #     context.update(t)
    # else:
    #     term = SearchTerms(term=query)
    #     term.save()
    return render(request, 'pages/search.html', context)


def record_post_like(request, pk, *args, **kwargs):
    post = get_object_or_404(Post, pk=pk)
    post.likes += 1
    post.save()
    return JsonResponse({'likes': post.likes})

books/views.py
import json
from django.conf import settings
from django.core import signing
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.http import Http404, HttpResponse, HttpResponseForbidden
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.html import strip_tags
from books.forms import AddressForm, AnonymousAddressForm

from books.models import Address, AnonymousAddress, AnonymousOrder, AnonymousPayedBook, AnonymousPayment, Book, Customer, Order, OrderItem, PayedBook, Payment
from books.utils import cookieCart, handle_payment, notify_email, ref_code_generator, sign_book_token, verifyTransaction

# Create your views here.


def bookView(request, *args, **kwargs):
    books = Book.objects.filter(published=True)
    return render(request, 'pages/book.html', {'books': books})


def bookDetail(request, pk, *args, **kwargs):
    book = Book.objects.get(id=pk)
    return render(request, 'book-detail.html', {'book': book})


def send_sample(email, book, user, request):
    from django.template.loader import render_to_string
    html = render_to_string("email/sample_book.html", {'book': book, "user": user, "request": request}
                            )
    plain = strip_tags(html)
    EmailFrom = "'Isaniro Books'<books@isaniro.com>"
    mail = EmailMultiAlternatives("Incamake y'igitabo '%s'" %
                                  book.title, html, EmailFrom, [email])
    mail.attach_alternative(html, "text/html")
    # mail.subject = "Incamake y'igitabo '%s'" % book.title
    # mail.body = html
    mail.attach_file(book.sample.path)
    # mail.to([email])
    mail.send(fail_silently=True)


def handleSampleRequest(request, pk, *args, **kwargs):
    book = get_object_or_404(Book, pk=pk)
    name = request.GET.get('name')
    email = request.GET.get('email')
    user = {"name": name, 'email': email}

    send_sample(email, book, user, request)
    return JsonResponse({"sent": True, "title": book.title})


def book_download(request, token, *args, **kwargs):
    signer = signing.TimestampSigner(
        key=settings.BOOK_SIGNATURE, salt="isaniro")
    try:
        data = signer.unsign_object(token)
        book = Book.objects.get(id=data['book'])
        return redirect(book.download_link)
    except Exception:
        print(Exception)
        return HttpResponseForbidden("Expired link")


def cart_view(request):
    if request.user.is_authenticated:
        customer, created = Customer.objects.get_or_create(user=request.user)
        order, created = Order.objects.get_or_create(
            customer=customer, completed=False)
        items = order.orderitem_set.all()
        cart_total = order.get_cart_total
        cart_quantity = order.get_cart_items
        context = {
            'items': items,
            'cart_total': cart_total,
            'cart_quantity': cart_quantity
        }

        return render(request, "cart.html", context)
    else:
        try:
            cart = json.loads(request.COOKIES['cart'])
        except:
            cart = {}
        cookie_cart = cookieCart(request)
        context = {
            'items': cookie_cart['items'],
            'cart_total': cookie_cart['cart_total'],
            'cart_quantity': cookie_cart['cart_quantity']
        }
        return render(request, "cart.html", context)


def addToCart(request, pk):
    book = Book.objects.get(id=pk)
    if not book.downloadable_copy:
        return HttpResponseForbidden("The book is not available")
    action = request.GET.get('action')
    if book:
        if request.user.is_authenticated:
            customer, created = Customer.objects.get_or_create(
                user=request.user)
            order, created = Order.objects.get_or_create(
                customer=customer, completed=False)
            orderItem, created = OrderItem.objects.get_or_create(
                order=order, product=book)
            if action == 'remove':
                orderItem.delete()
            else:
                orderItem.quantity = 1
                orderItem.save()
            return redirect("cart-view")
        else:
            return redirect("cart-view")
    return Http404("Not found")


def checkout_view(request):
    if request.user.is_authenticated:
        customer, created = Customer.objects.get_or_create(user=request.user)
        order, created = Order.objects.get_or_create(
            customer=customer, completed=False)
        if created:
            cookie_items = cookieCart(request)
            for item in cookie_items:
                try:
                    product = Book.objects.get(id=item['id'])
                    orderItem = OrderItem.objects.create(
                        product=product, order=order, quantity=item['quantity'])

                except:
                    pass

        items = order.orderitem_set.all()
        cart_total = order.get_cart_total
        cart_quantity = order.get_cart_items
        try:
            address = Address.objects.get(customer=customer)
            form = AddressForm(instance=address)
        except Exception:
            form = AddressForm()
        context = {
            'items': items,
            'cart_total': cart_total,
            'cart_quantity': cart_quantity,
            'form': form
        }

        if request.method == 'POST':
            try:
                address = Address.objects.get(customer=customer)
                form = AddressForm(request.POST, instance=address)
            except:
                form = AddressForm(request.POST)
            if not form.is_valid():
                context['form'] = form
                return render(request, 'checkout.html', context)
            if form.is_valid():
                print('Valid')

                address = form.save(commit=False)

                address.customer = customer
                address = address.save()
                print(address)
                host = request.get_host()
                protocol = request.scheme
                redirect_url = "%s://%s/book/payment-check" % (protocol, host)
                data = {
                    'transaction_id': order.order_id,
                    'get_cart_total': order.get_cart_total,
                    'customer_id': order.customer.user.id,
                    'customer_email': order.customer.user.email,
                    'name': order.customer.user.get_full_name(),
                }
                print(order.order_id)
                link = handle_payment(data, redirect_url)
                return JsonResponse({"link": link})

        return render(request, 'checkout.html', context)
    else:
        try:
            cart = json.loads(request.COOKIES['cart'])
        except:
            cart = {}
        cookie_cart = cookieCart(request)
        try:
            if not request.session.session_key:
                request.session.save()
            address = AnonymousAddress.objects.get(
                session_key=request.session.session_key)
        except:
            address = None
        form = AnonymousAddressForm(instance=address)
        context = {
            'items': cookie_cart['items'],
            'cart_total': cookie_cart['cart_total'],
            'cart_quantity': cookie_cart['cart_quantity'],
            'form': form
        }
        if request.method == 'POST':
            print(address)
            if address:
                form = AnonymousAddressForm(request.POST, instance=address)
            else:
                form = AnonymousAddressForm(request.POST)
            if form.is_valid():
                address = form.save(commit=False)
                if not request.session.session_key:
                    request.session.save()
                address.session_key = request.session.session_key
                address.save()
                order, created = AnonymousOrder.objects.get_or_create(
                    address=address, completed=False)
                if created:
                    for item in cookie_cart['items']:
                        try:
                            book = Book.objects.get(id=item.product.id)
                            order.products.add(book)
                            order.save()
                        except:
                            pass
                host = request.get_host()
                protocol = request.scheme
                print(address)
                redirect_url = "%s://%s/book/payment-check" % (protocol, host)
                data = {
                    'transaction_id': order.order_id,
                    'get_cart_total': cookie_cart['cart_total'],
                    'customer_id': ref_code_generator(),
                    'customer_email': address.email,
                    'name': address.full_name,
                    'telephone': address.telephone
                }
                print(order.order_id)
                link = handle_payment(data, redirect_url)
                return JsonResponse({"link": link})
            else:
                context['form'] = form
                return render(request, 'checkout-anonymous.html', context)
        return render(request, 'checkout-anonymous.html', context)


def provisionBooks(customer, payment, order):
    items = order.orderitem_set.all()
    for item in items:
        payedbook = PayedBook.objects.get_or_create(
            customer=customer, payment=payment, book=item.product)
    context = {

    }
    notify_email('email/download_book.html', customer.user.email, {})
    return True


def payment_check(request):
    status = request.GET.get('status', None)
    tx_ref = request.GET.get('tx_ref', None)
    tx_id = request.GET.get('transaction_id', None)
    info = verifyTransaction(tx_id)
    if info['data'] and info['data']['status'] == 'successful':
        if request.user.is_authenticated:
            try:

templates/detail.html
{% extends 'layout/base.html' %}
{% load static %}
{% load hitcount_tags %}
{% load humanize%}
{% load social_share %}

{% block title %}
{{post.title}}

{% endblock title %}

{% block header %}
<!-- Facebook tags -->
<meta property="og:url" content="{{request.build_absolute_uri}}" />
<meta property="og:title" content="{{post.title}}" />
<meta property="og:image" content="https://isaniro.com{{post.thumbnail.url}}" />
<meta property="og:image:alt" content="{{post.title|truncatechars:30}}" />
<!-- End of Facebook tags -->

<!-- Twitter tags -->
<meta name="twitter:image" content="https://isaniro.com{{post.thumbnail.url}}" />
<meta property="twitter:image:alt" content="{{post.title|truncatechars:20}}" />
<meta name="twitter:card" content="{{post.summary|safe|truncatechars:150}}" />
<meta name="twitter:site" content="@feytonf" />
<style>
    @import url('https://fonts.googleapis.com/css2?family=Bai+Jamjuree:wght@400;500;600&family=Lato&display=swap');

    .rendered-content p {
        font-family: 'Abel' !important;
        font-size: 1.2rem;
        color: black;
    }

    .rendered-content h3 {
        font-family: 'Bai Jamjuree' !important;
        font-weight: 500;
    }

    .loader-div {
        padding: 2rem;
        margin: 1rem auto;
        text-align: center;

    }

    .loader-div i {
        font-size: 3rem;
    }
</style>

{% endblock header %}

{% block content %}


<main>

    <!-- ---------------------- Site Content -------------------------->

    <section class="container">
        <div class="site-content">
            <div class="posts">
                <div class="post-content" data-aos="zoom-in" data-aos-delay="200">
                    <div class="post-image">
                        <div>
                            <img src="{{post.thumbnail.url}}" class="img" alt="blog1">
                        </div>
                        <div class="post-info flex-row">
                            <span><i class="fas fa-user text-gray"></i>&nbsp;&nbsp;{{post.author.name}}</span>
                            <span><i
                                    class="fas fa-calendar-alt text-gray"></i>&nbsp;&nbsp;{{post.published_date}}</span>
                            <span id="post-views" class="post-views">{% get_hit_count for post %} Views</span>
                            <span><i class="far fa-thumbs-up text-gray"></i>&nbsp;<b
                                    class="post-likes">{{post.likes}}</b></span>
                        </div>
                    </div>
                    <div class="post-title">
                        <a href="#post">{{post.title}}</a>
                        <div class="rendered-content" style="font-family: 'Abel';">
                            {{post.content|safe}}
                        </div>
                        <div class="like-button center">

                            <button class="btn btn-like require-login" data-post="{{post.pk}}" id="post-like-button"
                                data-url="{% url 'blog:add-post-like' pk=post.pk %}"><i
                                    class="far fa-thumbs-up fa-lg"></i></button>
                        </div>

                    </div>
                </div>
                <hr>
                <!-- <div class="author">
                    <div class="image"><img src="" alt=""></div>
                </div> -->

                <div class="post-content" data-aos="zoom-in" data-aos-delay="200">

                    <div class="comment section">
                        <h2 class="">Ibitekerezo</h2>
                        <form action="#https://google.com" method="POST" class="comment-form"
                            data-link="{% url 'blog:add-comment' pk=post.pk %}">
                            {% csrf_token %}
                            <input type="text" placeholder="Amazina" name="name" required minlength="5"
                                title="Izina rigizwe ninyuguti byibura 5" id="comment-name">
                            <input type="email" name="email" placeholder="E-mail" required
                                title="Andika email ikora neza" id="comment-email">
                            <textarea name="body" id="comment-body" cols="30" rows="3"
                                placeholder="Andika hano igitekerezo cyawe" required minlength="5"
                                title="Ubutumwa burengeje inyuguti eshanu"></textarea>
                            <input type="hidden" id="comment-bot" name="for-bot" hidden="true" value="none">
                            <button class="btn btn-primary" id="">Ohereza</button>

                        </form>
                    </div>

                </div>
                <br>
                <hr>
                <div class="comment-list" id="comment-list" data-url="{% url 'blog:comments-view' pk=post.pk %}">
                    <div class="loader-div">
                        <i class="fa fa-spinner fa-spin"></i>
                        <h2>Comment loading ...</h2>
                    </div>



                </div>
                <!--<button class="btn btn-primary comment" data-url="" id="load-comment_button">Load more</button>-->
            </div>
            <aside class="sidebar" style="font-family: 'Abel';">
                {% include "layout/cat.html" %}
                <div class="category">
                    <h2>Ibyiciro</h2>
                    <ul class="category-list">
                        <li class="list-items" data-aos="fade-left" data-aos-delay="100"><i
                                class="fab fa-facebook-f"></i>
                            {% post_to_facebook object_or_url "Sangiza kuri Facebook"%}

                        </li>
                        <li class="list-items" data-aos="fade-left" data-aos-delay="100">
                            <i class="fab fa-whatsapp"></i>
                            {% post_to_whatsapp object_or_url "Share via WhatsApp" %}

                        </li>


                    </ul>
                </div>
                <div class="popular-post">
                    <h2>Inkuru zisa niyi</h2>
                    {% for post in posts %}
                    <div class="post-content" data-aos="flip-up" data-aos-delay="200">

                        <div class="post-image">
                            <div>
                                <img src="{{post.thumbnail.url}}" class="img" alt="blog1">
                            </div>
                            <div class="post-info flex-row">
                                <span><i
                                        class="fas fa-calendar-alt text-gray"></i>&nbsp;&nbsp;{{post.published_date}}</span>
                                <span>{% get_hit_count for post %} Views</span>
                            </div>
                        </div>

                        <div class="post-title">
                            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                        </div>

                    </div>
                    {% endfor%}
                </div>
                <div class="newsletter" data-aos="fade-up" data-aos-delay="300">
                    <h2>Newsletter</h2>
                    <div class="form-element">
                        <input type="text" class="input-element" placeholder="Email">
                        <button class="btn form-btn disabled">Subscribe</button>
                    </div>
                </div>
                <div class="popular-tags">
                    <h2>Popular Tags</h2>
                    <div class="tags flex-row">
                        {% for tag in tags %}
                        <span class="tag" data-aos="flip-up" data-aos-delay="100">{{tag.title}}</span>
                        {% endfor %}
                    </div>
                </div>
            </aside>
        </div>
    </section>

    <!-- -----------x---------- Site Content -------------x------------>

</main>

<!---------------x------------- Main Site Section ---------------x-------------->
{% endblock content %}

{% block script %}

{% load hitcount_tags %}
{% get_hit_count_js_variables for post as hitcount %}
<script>

    (function ($) {
        $.postCSRF = function (url, data, callback, type) {
            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return /^(GET|HEAD|OPTIONS|TRACE)$/.test(method);
            }

            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== "") {
                    var cookies = document.cookie.split(";");
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) == name + "=") {
                            cookieValue = decodeURIComponent(
                                cookie.substring(name.length + 1)
                            );
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            var csrftoken = getCookie("csrftoken");

            // shift arguments if data argument was omitted
            if ($.isFunction(data)) {
                type = type || callback;
                callback = data;
                data = undefined;
            }

            return $.ajax(
                jQuery.extend(
                    {
                        url: url,
                        type: "POST",
                        dataType: type,
                        data: data,
                        success: callback,
                        beforeSend: function (xhr, settings) {
                            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                                xhr.setRequestHeader("X-CSRFToken", csrftoken);
                            }
                        },
                    },
                    jQuery.isPlainObject(url) && url
                )
            );
        };
    })(jQuery);

    jQuery(document).ready(function ($) {
        // use the template tags in our JavaScript call
        $.postCSRF("{{ hitcount.ajax_url }}", { hitcountPK: "{{ hitcount.pk }}" })
            .done(function (data) {
                //$('.post-views').text(data.hit_counted).attr('id', 'hit-counted-value').appendTo('#post-views');

                //$('#post-views').text(data.hit_message);
                console.log(data)
            })
            .fail(function (data) {
                console.log('POST failed');
                //console.log(data);
            });
    });

</script>
<script src="/static/js/detail.js" defer></script>

{% endblock script %}